version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=production
      - SERVER_ADDRESS=web
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: RESTfulAPI
      POSTGRES_DB: blogapi
